-- Kill Bill
CREATE USER IF NOT EXISTS '$KILLBILL_DATABASE_USER'@'%' IDENTIFIED BY '$KILLBILL_DATABASE_PASS';
GRANT USAGE ON *.* TO '$KILLBILL_DATABASE_USER'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `$KILLBILL_DATABASE_NAME`;
GRANT ALL PRIVILEGES ON `$KILLBILL_DATABASE_NAME`.* TO '$KILLBILL_DATABASE_USER'@'%';
